### ISSUE TITLE
feat: better error handling for recovery file

### ISSUE THREAD

**Issue by Nuhvi** [pubky/pubky-beta#153]
The current situation is, if anything went wrong with login, you will tell the user that their recovery file or recovery password is wrong, even if the problem is just that the homeserver is not reachable or has bad CORS settings, that is obviously very confusing and makes users think they forgot the password. https://github.com/synonymdev/social-ui-monorepo/blob/dev/apps/web/app/onboarding/sign-in/page.tsx#L149

**Comment by Nuhvi** [comment]
I think this issue is still relevant on https://staging.pubky.app/

**Comment by Nuhvi** [comment]
<img width="1307" alt="Screenshot 2024-08-01 at 11 17 28" src="https://github.com/user-attachments/assets/b58d2a45-3111-49e8-847f-7e2601dde8c1">

**Comment by flaviomoceri** [comment]
How can I reproduce this error now to get an error other than `Error: Invalid recovery file` or `Error: Invalid Encryption Key` ?

**Comment by Nuhvi** [comment]
@flaviomoceri Open `https://pubky.app/onboarding` then open dev tools, and change network settings to offline (or actually disconnect your internet), then try to upload a recovery file and write the passphrase, and sign in.

<img width="1005" alt="Screenshot 2024-08-29 at 17 28 04" src="https://github.com/user-attachments/assets/c68dc85c-b307-4887-a7b1-7587125c3a27">
