### ISSUE TITLE
feat: add `loading` spinner when you click `follow buton`.

### ISSUE THREAD

**Issue by MiguelMedeiros** [pubky/pubky-beta#165]
![image](https://github.com/synonymdev/social-ui-monorepo/assets/5798170/0f70ae47-358b-45cb-987e-8f8cfc4467f6)

**Comment by flaviomoceri** [comment]
Why do you want to add a Loading spinner, when I click on Follow me it's instant, it's not instant in production maybe?

**Comment by MiguelMedeiros** [comment]
> Why do you want to add a Loading spinner, when I click on Follow me it's instant, it's not instant in production maybe?

It is not instant in production; we need to give user a visual feedback.
