### ISSUE TITLE
bug: searching with some of the hot tags find posts without the same tag

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#196]
Searching with some of the tags listed in the hot tags section displays posts that are not currently using this tag.

https://github.com/synonymdev/pubky-app/assets/74595920/1c0f3c8c-5ee1-4f53-b57d-4c3cd1bd21db

**Comment by flaviomoceri** [comment]
We have to investigate, a post can have infinite tags and from the array we show the last 3 of the list.  So by searching for a tag you may find it in the list of posts even if that tag is not displayed in the UI.  With the new design this problem will be solved

**Comment by catch-21** [comment]
This did cross my mind, although wasn't sure how to prove. Feel free to close if the new design will definitely show all tags (or at least the ones being filtered for).
