### ISSUE TITLE
Backend input validation

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#228]
Any input validation in the frontend must be performed also in the backend. For example, 300 char limit, see https://mvp-001.nuh.dev/post/9arfi37owcrdywc9zqw3m5uc7gd5gqu1yfuykzo66od6tcayqk9y/2ZBFXCKJ48RG0.

**Comment by MiguelMedeiros** [comment]
We've already limited it to 300 characters on the front end. Could you please create an issue in the backend repo to apply the same 300-character limit there as well?
