### ISSUE TITLE
error emoji

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#246]
When I try to put an emoji in the middle of the text, it always goes at the end of the post

![Image](https://github.com/synonymdev/pubky-app/assets/46056211/cbba68fb-2216-46be-b00a-c1243d0c5205)

**Comment by flaviomoceri** [comment]
@JeanlChristophe can you please share a video with me, Im not able to reproduce it

![Screenshot 2024-06-19 102642](https://github.com/synonymdev/pubky-app/assets/63161412/40d27477-9c48-4c02-8c8b-5c601dd1383e)

**Comment by catch-21** [comment]
https://github.com/synonymdev/pubky-app/assets/74595920/eef5bdf7-d74d-465d-8300-97c6636ecff5

It happens for me when clicking the location I want the emoji to go and then using the emoji selector.
It doesn't happen for me when copy/paste the emoji.

Using Chrome Version 126.0.6478.61 (Official Build) (arm64)
