### ISSUE TITLE
Issue: seconds ago

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#275]
![Image](https://github.com/synonymdev/pubky-app/assets/46056211/4a9f8fdf-fe39-481e-a929-e9e861d9bbbd)
![Image](https://github.com/synonymdev/pubky-app/assets/46056211/170191ca-8ff8-49d1-9571-d9a9fbffd01e)

**Comment by flaviomoceri** [comment]
Already fixed https://github.com/synonymdev/pubky-app/issues/270
waiting next release 🙏
![Screenshot 2024-06-27 163633](https://github.com/synonymdev/pubky-app/assets/63161412/9731b81b-993d-4f6a-92a0-6530333383d8)
