### ISSUE TITLE
fix: sidebar image size elements

### ISSUE THREAD

**Issue by MiguelMedeiros** [pubky/pubky-beta#304]
check size of the images in the sidebar of the hot-tags page
![image](https://github.com/user-attachments/assets/0f6f028a-57c5-43d9-90ac-a14fdc1fe43d)
![image](https://github.com/user-attachments/assets/4aaed83c-f9c3-40d1-8f6b-ee60d2391239)

**Comment by flaviomoceri** [comment]
I checked and updated, it's so small
Please let's leave it like this, if anyone complains I'll update it 🙏

![Screenshot 2024-07-15 185738](https://github.com/user-attachments/assets/7df07c05-32dd-46f6-a395-092a0975ffac)
