### ISSUE TITLE
Duplicate posts shown in feed

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#312]
Only the first shows the reply so perhaps it is caused by the reply.

<img width="471" alt="Screenshot 2024-07-16 at 15 39 11" src="https://github.com/user-attachments/assets/bf66432d-f34e-45c5-af7b-902cfc2dc871">

**Comment by catch-21** [comment]
other example

https://github.com/user-attachments/assets/98e0425d-12cb-4672-a8b4-1ef94fb16180

**Comment by flaviomoceri** [comment]
Fixed, probably not perfect, but I think it's enough for now, I'll make it better once we use Nexus
If you think it's a bug, please reopen the bug 🙏
