### ISSUE TITLE
Deploy Pubky Staging

### ISSUE THREAD

**Issue by SeverinAlexB** [pubky/pubky-beta#327]
- Talk to the stakeholders and collect the requirements for our Pubky staging environment.
- Create a concept how to deploy and structure Pubky.
- Let the concept be reviewed by the stakeholders.
- Deploy to the Google Cloud staging.
- Present solution to stakeholders. Collect and implement feedback.

Stakeholders: @MiguelMedeiros @Nuhvi and @SeverinAlexB

Some involved topics:
- Correctly secure the home server seed.
- CD / CI

**Comment by flaviomoceri** [comment]
I think it's done
If you think it's a mistake, please reopen the issue 🙏
