### ISSUE TITLE
feat: schema for data exchange between front and backend

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#36]
@mainmode1 need this schema pretty soon

**Comment by MiguelMedeiros** [comment]
I'm looking at the @Nuhvi progress in the other repository and once I have a general idea of how the login will work, 
I'll work on this task.

**Comment by Nuhvi** [comment]
@MiguelMedeiros this should be merged soon https://github.com/slashtags/skunk-works/pull/14
