### ISSUE TITLE
remove element after download recovery file

### ISSUE THREAD

**Issue by Nuhvi** [pubky/pubky-beta#364]
https://github.com/pubky/pubky-app/blob/3f391f8ad77ab8370f70e3a607b6a7c6ceb97c43/apps/web/app/onboarding/confirm/page.tsx#L68

**Comment by flaviomoceri** [comment]
I tried to remove it, but if I do that and try to download the recovery file it doesn't work
I will close the issue, if you think I should try again please reopen the issue 🙏
