### ISSUE TITLE
'Explore' mode is more than a passive view-only mode

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#374]
When I first visit Pubky and am not signed in the option to 'Explore first' is presented. When clicked on the home page is loaded and posts can be viewed.

However, it is not obvious that this action creates a new keypair and I now have an active account with a profile named 'anonymous' that is capable of posting. An immediate recommendation is to "Back up your account" (https://github.com/pubky/pubky-app/issues/373), which isn't important when just wanting to explore. 

I expected a view-only mode and later decide to go through the onboarding process.

At this point:
1. Attempting to navigate back to `/onboarding` forwards me back to `/home`
2. There is no sign up button on the home page when anonymous

To go through the regular sign on process, I must navigate to my 'anonymous' profile and sign out.

Is this the flow we want?

Another drawback of the current approach is we will end up with a lot of dud anonymous accounts that will show up when searching.

**Comment by BitcoinErrorLog** [comment]
I think @aldertnl 's intention is for this to be like Bitkit, where you are merely pushing the backup process to later. We should probably discuss in a call if Pubky devs have any (important) concerns about throwaway accounts, but I am generally open to both approaches: 
1. An actual explore mode where you cannot interact at all without making an account on purpose
2. Always automatically making a key for people to encourage immediate engagement and incentive to create profile, etc

**Comment by aldertnl** [comment]
The current design for the Explore mode primarily supports a view-only mode (no keypair creation yet), with most interactions prompting the ‘Join’ dialog. Please also see the prototype for details. https://www.figma.com/proto/hkATVIievejljZHCQxnQbL/Pubky-App?page-id=5947%3A103199&node-id=5947-104436&viewport=176%2C-1516%2C0.58&t=0DRGzLsahwFj2mzK-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5947%3A103568&show-proto-sidebar=1&hide-ui=1
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/06a5090b-1f4f-44f5-b8c5-8bf7527f3340">

**Comment by JeanlChristophe** [comment]
Closing the ticket as it's already include into the design.
