### ISSUE TITLE
Notification badge is not responsive

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#375]
I have 3 notifications > I got and click on my profile > I can see the notifications. Once I refresh the number of notifications in the top right corner remains unchanged (i.e. I still see 3 notifications pending) even though I have checked them already 

<img width="933" alt="notification error" src="https://github.com/user-attachments/assets/10276384-a47d-4fa9-9feb-ddcec51d1cb7">

**Comment by catch-21** [comment]
Same for me. I get a new notification counter badge when someone follows me but this counter is not cleared once I have viewed the notification or even clicked 'Show All Notifications'.

**Comment by JeanlChristophe** [comment]
This feature is coming. Closing it.
