### ISSUE TITLE
Tag search button uses `[object Object]`

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#377]
Clicking on the magnifying glass icon uses tag `[object Object]` instead of the text value.

Click this icon -> ![Screenshot 2024-08-09 at 11 14 11](https://github.com/user-attachments/assets/e1d739a2-035a-44f3-9c23-87c05314cb8d)

![Screenshot 2024-08-09 at 11 12 05](https://github.com/user-attachments/assets/a77cd95f-96c1-46f7-a128-e8d133d9d401)

**Comment by ovitrif** [comment]
Here's how I encountered the same issue yesterday:

1. I was browsing this post
![objectObject1](https://github.com/user-attachments/assets/2f6fd7e1-4f9c-42a2-ae4d-930cf36cb3b7)

2. I clicked on :mag:
![objectObject2](https://github.com/user-attachments/assets/79aeac31-77eb-4e16-8cb3-37b313113b92)

3. Found the little bug 🐞 
![objectObject3](https://github.com/user-attachments/assets/51453341-610b-4b1c-aa73-7902d6552504)

@flaviomoceri Tested and it only repros on that specific :mag:, the one when you're on a post(with with tags) view
