### ISSUE TITLE
"Pubky copied to clipboard" should say "Pubkey" or "public key"

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#378]
When clicking button to copy profile's pubkey a message is shown saying "Pubky copied to clipboard".  This value is a "pubkey" or "public key" not a "pubky", so it should be changed.

![Screenshot 2024-08-09 at 14 33 29](https://github.com/user-attachments/assets/bac4cd08-7ab1-416b-ab08-96294d584eb5)

**Comment by flaviomoceri** [comment]
Also leave a message on figma to make sure @aldertnl can read it: [Figma Project](https://www.figma.com/design/hkATVIievejljZHCQxnQbL/Pubky-App?node-id=5781-169437&m=dev)
Thanks for the report 🙏

Figma:
![Screenshot 2024-08-09 163721](https://github.com/user-attachments/assets/8fcfe44b-6cfe-46e6-8d79-d73687bc28ca)

**Comment by aldertnl** [comment]
During the design process we decided to refer to the user identifier as ‘pubky.’ The advantage of using ‘pubky’ is that it naturally promotes our app’s brand whenever users talk about it in real life or share their pubky online across other platforms. It also instantly clarifies that it’s related to Pubky’s public key, eliminating any confusion about which key is being referenced. Even within Bitkit, we can refer to it as ‘pubky,’ helping users understand that this is a portable profile concept, usable across multiple platforms. The private key, meanwhile, can simply be referred to as ‘private key'.

**Comment by aldertnl** [comment]
<img width="847" alt="image" src="https://github.com/user-attachments/assets/0e43b588-99dc-496b-bebd-a642a8b4089d">

**Comment by flaviomoceri** [comment]
@Aldert if I try to copy another user's Pubky what should appear, I can't show "Your Pubky"

I think it makes sense to leave "Pubky copied to clipboard" as before to be always good

I will close this issue and refer to the figma, if you think it is a mistake, please reopen the issue 🙏
