### ISSUE TITLE
Copy Notifcation message appears for very short time

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#379]
When clicking button to copy profile's pubkey or link a message is shown for a very short time (no more than 1 second) which is not long enough to notice and read the whole message This provokes user to click two or more times to read what the notification said.

https://github.com/user-attachments/assets/208060f7-797d-4ff4-820e-42f72f226ffc

**Comment by flaviomoceri** [comment]
Increased to 2 seconds in the next version
Thanks for the report 🙏
