### ISSUE TITLE
Layout quirks when browser is not as full width

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#380]
1. Overlapping button and input field
![Screenshot 2024-08-09 at 09 51 13](https://github.com/user-attachments/assets/6a028ada-be55-4e7a-b7dd-920070c2a40b)

-----

**Comment by flaviomoceri** [comment]
We will probably take care of all these details as soon as we start the development of the mobile version. 
Thanks for the report 🙏

**Comment by flaviomoceri** [comment]
I'm closing it for now, if I think it's a mistake, please reopen the issue 🙏
