### ISSUE TITLE
User's profile link next to "Undo repost" includes "reposted"

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#383]
When a post is reposted and the original post is then deleted there is an option to "Undo repost" in the list of posts in your profile page.  Here there is a hyperlink to your profile on the text of your username.  The problem is that the hyperlink also includes the text "reposted".

To fix, either change the hyperlink to only apply on the username.

![1](https://github.com/user-attachments/assets/ca2ae1e4-ba6c-49b8-b907-ba9b7aee24a6)
In this example, my username is `v-v` but the hyperlink is applied to `v-v reposted`

**Comment by flaviomoceri** [comment]
fixed, linked PR #420
