### ISSUE TITLE
Navigating back to /sign-in without signing out doesn't forward back to /home

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#386]
Navigating back to `/sign-in` without signing out doesn't forward back to `/home`. As a result, it is possible to think you are signed out and when uploading a different key file to sign in with, you are directed to `/home` with the original account session.

Steps to reproduce:
1. Sign in with a new or existing account
2. Navigate to `/home` by typing in the url or pressing browser back button a few times
3. The sign in page is shown as if you were not signed in
4. Upload any key file, even if a profile for it doesn't exist in the homeserver
5. Input a pin
6. Click Sign In button
Observe it takes you to `/home` with the original account that still has an ongoing session.

It should either forward you to `/home` if you navigate to `/sign-in` with an active session or sign you out.

**Comment by flaviomoceri** [comment]
Fixed and pushed 
If it is still there, please reopen the issue
