### ISSUE TITLE
Can you setup a status UX

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#394]
A better UX is needed when creating a custom status (not self explanatory) perhaps a prompt is needed here as adding an emoji is mandatory but not highlighted anywhere. Maybe a "+" button

**Comment by catch-21** [comment]
<img width="348" alt="Screenshot 2024-08-16 at 10 10 31" src="https://github.com/user-attachments/assets/264aa076-b3cc-493d-9236-15ec170fdade">

A layout similar to slack with emoji before status text entry is more intuitive.

**Comment by flaviomoceri** [comment]
It should be better now, in the next release please try again, if so close

**Comment by catch-21** [comment]
better
