### ISSUE TITLE
Post tag layout bug

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#397]
When I added the tag 'blabla' with a monkey emoji to a post the layout pushes the monkey out of the UI element area. The counter (1) is also not aligned.

![Screenshot 2024-08-16 at 10 19 43](https://github.com/user-attachments/assets/bb9ee3c0-f9cf-46b5-bc6c-7821bba85584)

**Comment by flaviomoceri** [comment]
Fixed and pushed
If you think it's a mistake, please reopen the issue 🙏

**Comment by catch-21** [comment]
This issue exists on the current version that is using `pubky-nexus v0.1.0`. Reopening.
![Screenshot 2024-10-18 at 10 42 59](https://github.com/user-attachments/assets/a77d802a-84df-4c5e-aa5d-19691078b9c7)

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
Verified in latest staging deployment
