### ISSUE TITLE
'Traveling' status emoji icon is hard to see black-on-black

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#398]
Perhaps it should have a white outline or background given the app is always dark-mode.

![Screenshot 2024-08-16 at 10 02 49](https://github.com/user-attachments/assets/22959d77-05e9-474d-a9b7-0f34b2e678bb)

![Screenshot 2024-08-16 at 10 02 53](https://github.com/user-attachments/assets/3781705f-1e25-4023-8176-a64365d4987d)

**Comment by flaviomoceri** [comment]
😅, I can try to use something else, no idea because you see this emoji like this
![Screenshot 2024-08-16 113345](https://github.com/user-attachments/assets/5afc630f-027a-4da0-9abd-dbccb051eb56)

**Comment by catch-21** [comment]
Ah right. I am using Chrome Version 127.0.6533.100 (Official Build) (arm64) on MacOS Sonoma 14.5 (23F79). Probably a popular setup :)

**Comment by flaviomoceri** [comment]
There is no way to fix this, we are useing emojis, I'm closing it for now
If you think it's a mistake, please reopen the issue 🙏
