### ISSUE TITLE
I can't tag some people

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#399]
I am trying to tag John but I can't. nevertheless it's working for other people.

![Screenshot 2024-08-16 at 11 09 37](https://github.com/user-attachments/assets/149caa0a-d064-4e19-a81b-cfe39d313115)
![Screenshot 2024-08-16 at 11 10 04](https://github.com/user-attachments/assets/e07b6775-dc58-47c0-ba52-8ebe22d8028b)

**Comment by flaviomoceri** [comment]
The search works only with the new accounts created after the update. Cannot find old account using skunk-work, you have to type manually all the pubky of the user to mention him.

**Comment by JeanlChristophe** [comment]
Thanks
