### ISSUE TITLE
I can't add emoji when I repost a post

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#400]
I am currently trying to this post: https://mvp-001.nuh.dev/post/y4euc58gnmxun9wo87gwmanu6kztt9pgw1zz1yp1azp7trrsjamy/2ZMHFDZDGE500

But i can't add an emoji. Adding tag or media is working.
![Screenshot 2024-08-16 at 11 37 34](https://github.com/user-attachments/assets/8747473f-e340-4611-9850-e3b5f355ea6f)

**Comment by JeanlChristophe** [comment]
I am reopening the issue. it's not fix

**Comment by flaviomoceri** [comment]
This issue has been fixed and pushed

Linked PR #420 because now you can also post with just emojis

If you think it is a mistake, please reopen the issue 🙏
