### ISSUE TITLE
UX issue with tags in the search bar

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#401]
every time I type in the tag and press enter in the search bar the UX shows the word I typed in as well as the tag (see screenshot below)
<img width="749" alt="searchbar issue" src="https://github.com/user-attachments/assets/d2dc5fdc-fcd0-4131-9eb7-8593869235a4">

If I only choose the hot tags, there is no issue.

using Mozilla browser

**Comment by catch-21** [comment]
This bug is occurring on `feat/nexus-integration` branch
