### ISSUE TITLE
Sorting by popularity is killing the App

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#402]
When we are sorting by "Popularity"
![Screenshot 2024-08-16 at 11 52 50](https://github.com/user-attachments/assets/d85d9c77-369e-4ea9-b4bf-1243d8294f24)

It's killing the app with a black screen
![Screenshot 2024-08-16 at 11 52 56](https://github.com/user-attachments/assets/4d379222-3a02-494a-858e-1629b909f035)

**Comment by catch-21** [comment]
I see console error `TypeError: e.author.profile is undefined`

**Comment by flaviomoceri** [comment]
It works for me, I can't reproduce it
Is the error still there? Please explain how to reproduce it 🙏

**Comment by JeanlChristophe** [comment]
yes this is still the case for Pave, I and James.
In order to reproce it, you can click on "Popularity". you'll have a block screen.

**Comment by flaviomoceri** [comment]
If I use backend locally it works, if I use the one in production for some reason an error appears
I fixed it and now it works, but I'm not sure if it will work 100% also in production, so we'll see in the next release @JeanlChristophe

**Comment by flaviomoceri** [comment]
@JeanlChristophe Can you give it a quick try, does it work now?
https://mvp-001.nuh.dev/home

**Comment by JeanlChristophe** [comment]
Awesome it works now. Closing the ticket. Thanks Flavio
