### ISSUE TITLE
Empty tag

### ISSUE THREAD

**Issue by ovitrif** [pubky/pubky-beta#409]
Was able to add an empty tag yesterday…
Strange enough, after it was added, the little popup with the "user avatars trail" that is supposed to show only when you hover a tag, was showing even when I didn't hover it, always showed as I was browsing whenever that empty tag was on the page.

1. just browsing around, wanted to tag the post so I clicked the icon button
![emptyTag1](https://github.com/user-attachments/assets/5089e1d7-90a8-4d6c-877a-9164dd538695)

2. Landed on the usual full-screen modal
![emptyTag2](https://github.com/user-attachments/assets/e1943202-fa9d-4c6f-bd90-505998564aa2)

3. started with an unusual text
![emptyTag3](https://github.com/user-attachments/assets/d35e2c64-cc96-44b2-84d9-8a502de6bcfd)

4. changed into another unusual text
![emptyTag4](https://github.com/user-attachments/assets/972f6bcc-5c7e-4b87-94cf-86aa8abf7ecf)

6. did something to land on the feed
   with an empty tag and a component that's not supposed to be seen unless one hovers the tag
![emptyTag5](https://github.com/user-attachments/assets/ad0b2531-9908-423d-979a-e0d4a0036712)

**Comment by ovitrif** [comment]
@flaviomoceri Tried to repro the flow, I suppose my exclamation mark brakes it?!

Here's the steps:

1. Click icon to add tag
2. Entered `w=qa` and tapped the `➕`
3. Entered `qa!` and pressed the `ENTER` key
4. Ended up with a similar result:
![Arc 2024-08-21 004175](https://github.com/user-attachments/assets/9734499f-dc7f-410b-b7e7-d54dc3891bbd)

**Comment by flaviomoceri** [comment]
Fixed and pushed
If you think it is a mistake, please reopen the issue 🙏
