### ISSUE TITLE
Wrong dimension for profile picture

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#421]
Once I upload an image, this one is ugly.`

**Original**
![106447581-1584435213898gettyimages-1207384868-3220310985](https://github.com/user-attachments/assets/89c556db-9146-4138-905d-85b4abf01a56)

**Result**
![Screenshot 2024-08-28 at 13 16 26](https://github.com/user-attachments/assets/6f74ecce-11ab-4085-8edb-7d3d0c82732b)

**Comment by flaviomoceri** [comment]
Fixed and linked to #420
