### ISSUE TITLE
Wrong "Edit" post

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#423]
When clock on edit a post, I can Edit my profile

![Screenshot 2024-08-28 at 13 34 23](https://github.com/user-attachments/assets/7d5911fe-ce50-4f54-856f-51062fb34d4e)

**Comment by flaviomoceri** [comment]
I don't see any "Edit Post", it's a feature not present on Pubky, you are able to edit your profile through that menu post because it's your post

If you think it's a mistake, please reopen the issue 🙏
