### ISSUE TITLE
Bug? I tagged a post but I don't see it under my Tagged section

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#424]
<img width="877" alt="tag " src="https://github.com/user-attachments/assets/c63aaa00-53d4-4b0d-ae43-7ed45be89c19">

not sure if this is a bug but I can't see the tag under my "Tagged" section.

**Comment by catch-21** [comment]
<img width="1234" alt="Screenshot 2024-08-28 at 12 48 12" src="https://github.com/user-attachments/assets/97055ed9-4be3-46df-84a4-639eae74b205">

Looks like the tags for this profile are being shown rather than the tags this profile has made.

**Comment by flaviomoceri** [comment]
Under the "tagged" section you only see tags related to your profile, not related to posts

It's not a bug, if you think it's a mistake, please reopen the issue🙏

**Comment by catch-21** [comment]
Now I check, it is matching the design. Thanks for closing.
