### ISSUE TITLE
Bookmarks don't show a number (see screenshot)

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#425]
<img width="689" alt="bookmarks bug" src="https://github.com/user-attachments/assets/ed69a899-5357-4881-8078-469bd8ab6706">

I can see I've successfully bookmarked a post, but I don't see a number next to Bookmarks in my profile section

**Comment by flaviomoceri** [comment]
To get this information we need help from the backend guys @JeanlChristophe  

But instead of modifying skunk-works, I think it's better to make sure this feature is present on Nexus
