### ISSUE TITLE
"Show All Notifcations" button is shown when all notifications are being shown

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#426]
<img width="1284" alt="Screenshot 2024-08-28 at 12 45 00" src="https://github.com/user-attachments/assets/3779ef15-df98-4a2c-acb3-d9a1515688a8">

When viewing notifications on your own Profile page, there is a button to "Show All Notifications" when all notifications are already being shown. This button/link is only useful when there are too many notifications to view on the profile page.

**Comment by flaviomoceri** [comment]
fixed and linked #420
