### ISSUE TITLE
[Bug] Search Bar can return duplicate entries

### ISSUE THREAD

**Issue by thisispav** [pubky/pubky-beta#427]
<img width="916" alt="search bar issue" src="https://github.com/user-attachments/assets/eb1a55d8-fbb4-4bd1-8439-0778387eafa2">

when I type in a letter I get multiple instances of the same profile (refer to screenshot)

**Comment by catch-21** [comment]
This profile is https://mvp-001.nuh.dev/profile/9sq3zoyhz9adgxtx5z1yy7ffqyur6njmc6jg8sghc36mgcjjdtxo
The username has 2x character 'f' and the pubky has 2x character 'f', which might explain the 4 instances of this serach result.

**Comment by flaviomoceri** [comment]
To fix it, I would need the help of the backend guys @JeanlChristophe but I think it's better to make sure it works on Nexus

**Comment by MiguelMedeiros** [comment]
Fixed in the current version.

**Comment by catch-21** [comment]
Verified in current staging deployment
