### ISSUE TITLE
Search bar doesn't return entries for all matching profiles on home page

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#428]
<img width="1261" alt="Screenshot 2024-08-28 at 13 20 28" src="https://github.com/user-attachments/assets/7db5f0cb-7810-479f-b3d3-7bb1b44b4164">

On the home page, I am searching for profile https://mvp-001.nuh.dev/profile/9sq3zoyhz9adgxtx5z1yy7ffqyur6njmc6jg8sghc36mgcjjdtxo which was created recently by typing letter 'F' into the search bar. The only entry returned is Flavio.
We know from https://github.com/pubky/pubky-app/issues/426 that this profile can be found be searching from the /search page, so why not also the /home page?

**Comment by flaviomoceri** [comment]
I can't reproduce the error, it seems like multiple search results appear

How can I replicate this?

Anyway I see that it doesn't show all the results and some of them replicate, there is a bug
To fix it, I would need the help of the backend guys @JeanlChristophe , but I think it's better to make sure it works on Nexus

![Screenshot 2024-08-28 160951](https://github.com/user-attachments/assets/2a18bee6-ef33-4f0e-a9b0-a41ca865f6f1)

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
Verified in latest staging deployment.
