### ISSUE TITLE
[Bug]: Profile names are unnecessarily truncated in list on Profile page

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#452]
### Describe the bug

See screenshot, there is lots of space to show more of the profile names.

### Reproduce

1. Go to a Profile page
2. Click one of the tabs (following, folowers)
3. Observe list of Profiles. Names are truncated even though there is space to view more.

### Screenshots / Recording

<img width="944" alt="Screenshot 2024-09-04 at 13 26 31" src="https://github.com/user-attachments/assets/87b99158-ae28-4eb6-bcd7-2d56bc7f03d7">

### Web Browser

Version 128.0.6613.86 (Official Build) (arm64)

### Pubky App Version

v0.12

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
Verified in latest staging deployment
