### ISSUE TITLE
[Bug]: "Loading" can display indefinitely on Profile page

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#459]
### Describe the bug

It is possible to open the Profile page too quickly so that the username shows "Loading..." indefinitely and other contents never loads. So far, I have only seen this with the automated tests because they perform actions quickly. I have slowed Cypress down to prevent this causing inconsistent results in our pipeline test runs.

This is likely due to the Github runners being a bit slow. Nevertheless, it would be a good idea to handle this in the frontend incase of any unexpected delays in production.

### Reproduce

Reduce the Cypress `commandDelay` and run any of the tests in CI

### Screenshots / Recording

https://github.com/user-attachments/assets/78c56c3d-3b3f-4fe7-b0fa-641954ff9f9e

### Web Browser

Version 128.0.6613.86 (Official Build) (arm64) & Firefox 129.0.2 (64-bit)

### Pubky App Version

v1.13.3 6e7201040d91e4ee8ec9dec26f288df3733d1066

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
Verified in a586206b8e222e73ff937a2f59960ab39abaede6
