### ISSUE TITLE
[Bug]: Referencing a profile in a post only works in lower case

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#461]
### Describe the bug

When creating a new post, it is possible to refer to a profile by typing `@` followed by their name.  This only seems to work if you type using lower case letters, not upper case.  It should be case insensitive, or if it is case sensitive then it should work with upper-case for profile names that start upper-case.

### Reproduce

1. On the feed page
2. Click in the quick post area at the top of the feed
3. Type `@A`
4. Observe no suggestions for profiles to reference
5. Clear the text entry area and type `@a`
6. Observe suggestions for profiles beginning with 'a' or 'A'

### Screenshots / Recording

<img width="732" alt="Screenshot 2024-09-11 at 14 57 11" src="https://github.com/user-attachments/assets/07a72b5c-f149-45c6-8305-58143c080b53">

-----

<img width="750" alt="Screenshot 2024-09-11 at 14 57 03" src="https://github.com/user-attachments/assets/2577e3b1-8e40-452d-a9ab-341e88c13c67">

### Web Browser

Version 128.0.6613.120 (Official Build) (arm64)

### Pubky App Version

v0.12

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
