### ISSUE TITLE
[Bug]: Typo: "Not tags yet"

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#464]
### Describe the bug

Seen when creating a post and when tagging an existing post.

Should this be "No tags yet" or "Not tagged yet" ?

### Screenshots / Recording

<img width="491" alt="Screenshot 2024-09-12 at 21 13 10" src="https://github.com/user-attachments/assets/d7412463-7d6e-44b0-b1d2-9c0676d1c2e2">

<img width="851" alt="Screenshot 2024-09-12 at 21 13 27" src="https://github.com/user-attachments/assets/aa13ca83-8e27-4b0d-a1f9-4face778b7ea">

### Pubky App Version

v0.12

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
