### ISSUE TITLE
[Bug]: Reposting a repost cause black screen and console error

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#465]
### Describe the bug

If the repost button is pressed on a post I have already reposted then the whole page goes black and a console error occurs: `TypeError: Cannot read properties of undefined (reading 'toString')`

Update: This only occurs when the repost being reposted has no content!

### Reproduce

1. Find a post in the feed
2. Repost the post **without adding any content**
3. Find your repost in the feed
4. Repost it again
5. Observe whole screen goes black

### Screenshots / Recording

https://github.com/user-attachments/assets/5de77aae-0e7e-4458-9ce9-f4628410e612

### Web Browser

Version 128.0.6613.120 (Official Build) (arm64)

### Pubky App Version

v0.12

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
Verified in a586206b8e222e73ff937a2f59960ab39abaede6
