### ISSUE TITLE
[Bug]: Reposting, Replying, and deleting a reply do not immediately display,  manual refresh required

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#466]
### Describe the bug

Unlike a regular creation or deletion of a post, **reposting, replying, and deleting a reply** do not immediately display in the feed. A manual page refresh is required. It would be nice if every user action that affects the feed is immediately shown.

### Reproduce

1. Repost an existing post, or reply to an existing post
2. Observe that the feed doesn't immediately show your repost/reply
3. Manual refresh required to see the change

### Screenshots / Recording

Repost

https://github.com/user-attachments/assets/39c6cb25-9181-4710-9e65-79b4a0fef6b4

-----

Reply

https://github.com/user-attachments/assets/eace5ad1-a496-44f8-8c89-7e7aecd9e22c

### Web Browser

Version 128.0.6613.120 (Official Build) (arm64)

### Pubky App Version

v0.12

**Comment by MiguelMedeiros** [comment]
Now that we have changed the information flow, when you post something you will receive a pop-up message notifying you that it has been successfully posted to the homeserver and in a few seconds your timeline will appear with a "show more posts" button.

**Comment by catch-21** [comment]
Tested in 24840dce71c2d092cf624de182fb1a9d7df88258
Only reposting appears to be good. The following still require manual refresh:
- Replying
- Deleting a reply
- Undoing a repost

**Comment by catch-21** [comment]
Verified and removed workarounds from E2E tests
