### ISSUE TITLE
[Bug]: Tooltip menu for a post can overlay the page header

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#467]
### Describe the bug

When the tooltip menu for a post in feed is displayed then it stays visible when scrolling, which might be ok, but it can appear ontop of the header and search bar, which does not look great.

### Reproduce

1. Click on the menu button for any post in feed
2. Scroll down

### Screenshots / Recording

https://github.com/user-attachments/assets/c1b43e29-2277-43c9-88b2-9c251fedd18d

### Web Browser

Version 128.0.6613.138 (Official Build) (arm64)

### Pubky App Version

v0.12

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
