### ISSUE TITLE
[Feature]: Backup filename to use client's timezone

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#468]
### Describe the problem

The filename of a backup file is formatted like `pubky_recovery_2024-09-16.pkarr` and this date is decided by skunkworks to always use UTC, see [here](https://github.com/pubky/skunk-works/blob/6cea300b05f22b9a8581a51195eccb59ad00e654/packages/sdk/src/lib/recovery.js#L46). This could be misleading for those in different time zones.

### Describe the solution

It be made relevant to the client timezone.

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
no timestamp in file now
