### ISSUE TITLE
[Bug]: Unable to view uploaded svg image in post (400 Bad Request)

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#477]
### Describe the bug

It is possible to upload an svg image in a post but it cannot be retrieved in the feed.
For example this post fails: https://mvp-001.nuh.dev/post/pxnu33x7jtpx9ar1ytsi4yxbp6a5o36gwhffs8zoxmbuptici1jy/2ZVA81HMZRYG0
But the svg image exists on the backend: https://secretproject.nuh.dev/mvp/pubky.app/static/pxnu33x7jtpx9ar1ytsi4yxbp6a5o36gwhffs8zoxmbuptici1jy/2ZVA81HC99TG0

### Reproduce

1. Download or create an svg image file
2. Create a new post with the svg image file attached
3. View the post in feed
4. Observe broken image link

### Screenshots / Recording

<img width="638" alt="Screenshot 2024-09-24 at 14 52 32" src="https://github.com/user-attachments/assets/370e452b-301c-4dad-bd31-17168df489a3">

### Web Browser

Version 128.0.6613.138 (Official Build) (arm64)

### Pubky App Version

v0.12

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
Although the svg shows in feed, if the image is clicked on there is an error in the modal view, https://github.com/pubky/pubky-app/issues/612
