### ISSUE TITLE
[Bug]: Quick post shows profile name as  'anonymous'

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#492]
### Describe the bug

After signing in with an existing profile that has the name 'jamses' the quick post still shows 'anonymous'. This is still the case after clearing local cache and refreshing.

### Reproduce

1. Sign up using a unique profile name (I also have edited this name a few times, not sure if significant for this bug)
2. Sign out or use a different browser state to proceed to sign in
3. Sign in as the newly created account
4. Observe username in quick post area

### Screenshots / Recording

<img width="384" alt="Screenshot 2024-10-16 at 09 52 02" src="https://github.com/user-attachments/assets/fbd9e69c-c793-4914-9533-7f7f02e369fe">

<img width="864" alt="Screenshot 2024-10-16 at 09 59 07" src="https://github.com/user-attachments/assets/3ac2fff6-423a-4797-a2af-29e2a99b985b">

### Web Browser

Chrome Version 129.0.6668.100 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
I have seen this happen a few times randomly, sometimes it shows a previous user profile's name instead of the one I just signed in as. Unsure how to reliably recreate.

**Comment by flaviomoceri** [comment]
Wait for the next release, make sure to remove caches and try again
If the problem persists I will try to reproduce it

**Comment by MiguelMedeiros** [comment]
Not happening on the latest version.

**Comment by catch-21** [comment]
Not seen this for weeks. Closing.
