### ISSUE TITLE
[Feature]: Sign in should allow using valid backup with no associated profile

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#496]
### Describe the problem

When signing in with a valid pubky backup but that does not have a profile associated, pubky-app prevents the user from proceeding with this key. "Failed to fetch user profile" error is displayed. This can occur when using a backup from an old server, other environment, or if the profile has been deleted.

![image](https://github.com/user-attachments/assets/2ac1d30a-b256-4e5e-a695-8f8998a92f26)

### Describe the solution

Pubky-app should prompt user to add new profile info: name, bio, etc. This is a good option because it explicitly tells the user they do not yet have a profile.

### Additional context

See internal discussion https://synonymworkspace.slack.com/archives/C031F2DC1JM/p1729059765553779

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
I've modified the title and description because I think it would bean improvement to allow use of valid backup file or seed phrase.
