### ISSUE TITLE
[Bug]: hyphen in tags causes line break

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#497]
### Screenshots / Recording

![image](https://github.com/user-attachments/assets/87632377-3c59-4957-a1d0-f86f42643eb3)

### Web Browser

chrome

### Pubky App Version

oct 16

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again

**Comment by MiguelMedeiros** [comment]
fixed

**Comment by catch-21** [comment]
Verified in bc641aa3901478710b09cd62717d24cf260e4f25
