### ISSUE TITLE
[Bug]: site ico is stretched width

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#499]
### Describe the bug

icon in tab bar of browser is showing and stretched to fit the width. it should hold its original vertical proportion instead

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/65013152-63e6-4df1-b7f9-c6774268b60c)

### Web Browser

chrome

**Comment by flaviomoceri** [comment]
Fixed now, in the next release please try again

**Comment by MiguelMedeiros** [comment]
fixed

**Comment by catch-21** [comment]
verified in bc641aa3901478710b09cd62717d24cf260e4f25
