### ISSUE TITLE
[Bug]: too many font changes on Profile page

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#502]
### Describe the bug

Regardless of what may be in the prototype (i didnt check) this page has too many font variations. At minimum we could start by enlarging the size of the font in the left side menu, to be the same as button & tag text 

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/f7bd887e-3c3d-425e-9189-462c95d9ab4c)

### Web Browser

chrome

**Comment by BitcoinErrorLog** [comment]
tagging @aldertnl just in case this needs proto changes to reduce fonts

**Comment by MiguelMedeiros** [comment]
This is an old design version. Please check Figma again and re-open this issue if it's necessary.
