### ISSUE TITLE
[Bug]: notification circle too large/grey

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#503]
### Describe the bug

I want this notification circle to be either pubky-green, or notification-red... or maaaaybe perfect white. @aldertnl 

It is also too large, should reduce by 3-6px

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/c1d82bc6-33e6-48d8-9fa9-dce641b4aa8d)

### Web Browser

chrome

**Comment by BitcoinErrorLog** [comment]
I want this notification circle to be either pubky-green, or notification-red... or maaaaybe perfect white. @aldertnl

It is also too large, should reduce by 3-6px

**Comment by flaviomoceri** [comment]
It should be fixed, but please check in the next release

**Comment by aldertnl** [comment]
Please change to #C8FF00

**Comment by flaviomoceri** [comment]
done

**Comment by MiguelMedeiros** [comment]
fixed

**Comment by catch-21** [comment]
Verified in bc641aa3901478710b09cd62717d24cf260e4f25

| Figma  | App |
| ------------- | ------------- |
| ![Image](https://github.com/user-attachments/assets/d4bec872-9721-4013-bda3-9815c5f60531) | ![Image](https://github.com/user-attachments/assets/8ceb7cbe-de0f-4bbc-8ab2-2e1c5420b85f) |
