### ISSUE TITLE
[Bug]: cap-height and baseline need to line up in header lettering

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#504]
### Describe the bug

[Bug]: The cap-heights need to match, and the baselines need to line up in the header letters of the logo & titles for each section, like "Profile" @al

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/ea2e928a-c569-4a1d-8332-bbb843e22616)

### Web Browser

chrome

**Comment by BitcoinErrorLog** [comment]
Refer to @aldertnl on what i mean if needed, and Aldert plz update the proto if needed

**Comment by MiguelMedeiros** [comment]
Fixed in the latest version.
