### ISSUE TITLE
[Bug]: Threads graphics are inconsistent

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#505]
### Describe the bug

1. The the connecter lines are not the same stroke thickness as the straight line (they are too thin). 
2. We should never show broken connectors, or connector to nowhere

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/6a806a7a-38d2-4833-8b2b-5b0a002d68ea)

### Web Browser

chrome

**Comment by BitcoinErrorLog** [comment]
also 
![image](https://github.com/user-attachments/assets/72adfe8d-0c34-430c-8184-c9018e9d881f)

**Comment by flaviomoceri** [comment]
Fixed, wait for next release

**Comment by MiguelMedeiros** [comment]
Fixed

**Comment by catch-21** [comment]
Verified in bc641aa3901478710b09cd62717d24cf260e4f25
Appears to all be fixed now.
 
![Image](https://github.com/user-attachments/assets/39962a05-7047-418b-802a-5db598a33bd1)

![Image](https://github.com/user-attachments/assets/bc75a37d-130b-4dd8-8d7a-7c82d0d55074)
