### ISSUE TITLE
[Bug]: image viewer should not enlarge

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#506]
### Describe the bug

if the image is too small, i think we should just center it and show at 72ppi (i assume this is still standard), not enlarge it beyond its provided resolution. (But it is still ok to reduce an image to fit the box if it is too large)

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/e4bd9c0b-c35a-4f9f-8347-3ca1bf5cf7a9)

### Web Browser

chrome

**Comment by MiguelMedeiros** [comment]
Done.
