### ISSUE TITLE
[Bug]: Can only choose one tag to filter with

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#507]
### Describe the bug

1. I can only choose one tag to filter with, i should be able to choose more
2. after i choose a tag, i lose the ability type in the search bar field (to add another one)

### Screenshots / Recording

https://github.com/user-attachments/assets/5cfea9d6-a10c-4d15-bfe9-f777adcbc0ec

### Web Browser

chrome

**Comment by flaviomoceri** [comment]
Fixed, wait for next release

**Comment by catch-21** [comment]
Tested on bc641aa3901478710b09cd62717d24cf260e4f25
This is part-fixed.

Good:
- I can select up to three tags from the hot tags list to search
- I can type a tag name to search 

Bad:
- Once there is one or more tags applied to the search I cannot type to apply an additional tag
