### ISSUE TITLE
[Bug]: Numbers in tags are too dark

### ISSUE THREAD

**Issue by BitcoinErrorLog** [pubky/pubky-beta#508]
### Describe the bug

Numbers shown within tags are a little bit too dark, can we tweak the opacity to be a little whiter? 

### Screenshots / Recording

![image](https://github.com/user-attachments/assets/39f9f2ef-b9a6-4298-a10b-052776e6239c)

### Web Browser

chrome

**Comment by BitcoinErrorLog** [comment]
Numbers shown within tags are a little bit too dark, can we tweak the opacity to be a little whiter?  @aldertnl

**Comment by flaviomoceri** [comment]
from text-opacity-30 to text-opacity-60

**Comment by aldertnl** [comment]
50 should be ok I think

**Comment by flaviomoceri** [comment]
wait next release

**Comment by catch-21** [comment]
verified in bc641aa3901478710b09cd62717d24cf260e4f25

| Figma  | App |
| ------------- | ------------- |
| ![Image](https://github.com/user-attachments/assets/12b32852-e62e-4310-9ae6-35f871d7a2ec) | ![Image](https://github.com/user-attachments/assets/669f4773-c694-47f6-a547-949535451242) |
