### ISSUE TITLE
[Bug]: Some lists reload unnecessarily on browser tab revisit

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#509]
### Describe the bug

Some lists, such as Muted Users, will reload when navigating back from a different browser tab. This shows the loading spinner which can take many seconds to resolve, meanwhile the original list content cannot be seen.

Given it is unlikely the state of the list will change in this scenario, it probably doesn't need reloading unless the page is refreshed or revisited. 

We don't appear to do this in other areas, although there could be some other example.

Places where this occurs:
- Muted Users settings page https://privky.app/settings?section=muted_users
- Profile bookmarks https://privky.app/profile?tab=bookmarks

### Reproduce

To reproduce for muted users:

0. Have at least one muted user
1. Go to Muted Users settings page
2. Wait for list of muted users to be displayed
3. Opens a new browser tab
4. Click on the pubky-app browser tab to show the app again
5. Observe loading spinner where list of muted users was, wait for it to resolve before viewing the same list as before

### Screenshots / Recording

https://github.com/user-attachments/assets/f66dbb95-2b5a-446a-8e9e-3ceb2ec499f3

https://github.com/user-attachments/assets/d6dd7634-5b5c-4771-b7da-9cf9473b8131

### Web Browser

Version 129.0.6668.100 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
Verified in a586206b8e222e73ff937a2f59960ab39abaede6
no long loading
