### ISSUE TITLE
[Feature]: Improve error when invalid recovery file and pin

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#510]
### Describe the problem

When using a valid recovery file with the wrong pin the error is
<img width="363" alt="Screenshot 2024-10-16 at 22 58 12" src="https://github.com/user-attachments/assets/a12f59e6-67f3-4eb2-8c56-fbc88b4a84b5">

### Describe the solution

Make the error more user friendly

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
