### ISSUE TITLE
[Bug]: Unable to upload large image or video media in post (status code 413)

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#522]
### Describe the bug

When attaching an image or video file greater than 1MB I see a "Something went wrong" error and the request has status code `413 Request Entity Too Large`.
When doing the same with a media file larger than 20MB the error is "The maximum allowed size is 20 MB", which suggests smaller files should work.

### Reproduce

1. Attach a image or video file that exceeds 1MB to a post (I tried with jpg and mp4)
2. Click 'Post' button
3. Observe "Something went wrong error".  Dev tools shows `413 Request Entity Too Large` for the PUT.

### Screenshots / Recording

https://github.com/user-attachments/assets/f81d1489-4992-4de7-8d20-48f9bd58292e

![pexels-frans-van-heerden-201846-17238031](https://github.com/user-attachments/assets/7572be15-20f0-4c25-94fa-9f3ee62ad36e)

### Web Browser

Version 130.0.6723.59 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0 ©

**Comment by SeverinAlexB** [comment]
Wanted to post this image. Didn't work either. It's only 132KB big.
![image](https://github.com/user-attachments/assets/a4371211-e7b0-4372-901e-a0d459bbeeb1)

Console output:
![image](https://github.com/user-attachments/assets/8ddfdfaf-b58b-4a8a-a323-6d45e076e937)

**Comment by weedcoder** [comment]
the 413 error entity too large is delivered by nginx, the reverse proxy in front of pubky services.
to address this problem, client body size limitations checks are removed in nginx configuration.

**Comment by catch-21** [comment]
Looks fixed to me in staging, thanks @weedcoder.
