### ISSUE TITLE
[Bug]: Unable to delete immediately after creating a new post

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#523]
### Describe the bug

After creating a new post it is immediately seen in the feed. At this point, attempting to delete it causes "Something went wrong" error and 404 Not Found status code for DELETE request. Must refresh browser to retry successfully/

### Reproduce

1. Enter some text into quick post box and click 'Post'
2. Wait for post to appear in feed
3. Click on dropdown menu for the newly created post and click 'Delete'
4. Observe "Something went wrong" error, even after retrying
5. Refresh page and retry delete, it'll work.

### Screenshots / Recording

https://github.com/user-attachments/assets/226bf232-61ff-4446-a246-9fcbff88b912

### Web Browser

Version 130.0.6723.59 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0 ©

**Comment by MiguelMedeiros** [comment]
Fixed with the new flow.

**Comment by catch-21** [comment]
Verified in 24840dce71c2d092cf624de182fb1a9d7df88258
