### ISSUE TITLE
[Bug]: Tab counters in profile do not always reflect the number of items listed

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#525]
### Describe the bug

Just after following someone, navigating back to my own profile shows them listed in the 'Following' tab but the counter still has not updated. They should both stay in sync.

### Reproduce

1. Follow a profile
2. Immediately navigate to own profile
3. Click on 'Following' tab
4. Observe number of listed items is not the same as a counter

### Screenshots / Recording

<img width="990" alt="Screenshot 2024-10-24 at 09 10 39" src="https://github.com/user-attachments/assets/40dddea9-c63c-42e9-864b-3807b34709d9">

### Web Browser

Version 130.0.6723.59 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

The only problem is with posts tab that show only posts but counts posts + replies, it will be fixed soon

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
