### ISSUE TITLE
[Bug]: Notifications not being listed in own profile

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#526]
### Describe the bug

I have 1 new notification (probably that someone tagged my post) but it is not listed on own profile page. The list is blank.
It doesn't look like any network requests are being made.

### Reproduce

1. Have at least 1 new notification
2. Navigate to own profile
3. View 'Notifcations' list in tab
4. Observe list is blank (not even the "no notifications" text is shown)

### Screenshots / Recording

<img width="982" alt="Screenshot 2024-10-24 at 09 18 40" src="https://github.com/user-attachments/assets/082ac2fb-6bab-4882-914a-453589ae3f09">

### Web Browser

Version 130.0.6723.59 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verifiied in a586206b8e222e73ff937a2f59960ab39abaede6
I think there is still work needed for notifications before testing properly
