### ISSUE TITLE
[Bug]: Unable to untag profile or add to existing tag on profile

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#527]
### Describe the bug

Clicking on a tag I just added to my own profile does not untag.  Tried from own profile page, the Tagged tab, add tag modal.
I also cannot add to an existing tag on a profile that someone else added by clicking on it.

### Web Browser

Version 130.0.6723.59 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
