### ISSUE TITLE
[Bug]: Unable to follow new user for a while

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#529]
### Describe the bug

When a new user is created, navigating to their profile shows their follow button as "Loading..." and the rest of their profile information is correctly displayed.
This is the case for many minutes, even after refreshing the page. After a while the button will read "Follow".
It should be possible to follow an account 

### Reproduce

1. Create a new profile
2. Copy its pubky
3. From an existing profile, type the new profile's pubky into the search bar and press enter
4. Observe the profile page is loaded but the follow button shows "Loading..." and this is the case for multiple minutes even if you refresh the page.

### Web Browser

Version 130.0.6723.59 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
unable to verify due to https://github.com/pubky/pubky-app/issues/614

**Comment by catch-21** [comment]
Verified in 21c859c8fd9ae52bc43431720ad96288baf511da
