### ISSUE TITLE
[Bug]: replies duplicated in post page

### ISSUE THREAD

**Issue by flaviomoceri** [pubky/pubky-beta#533]
### Describe the bug

Navigate inside a post with a reply, if you scroll it will trigger the page and show the same post duplicated many times

### Screenshots / Recording

![Screenshot from 2024-10-31 13-45-18](https://github.com/user-attachments/assets/c04c926a-7436-45e4-92ad-7d440b8da309)

**Comment by MiguelMedeiros** [comment]
fixed
