### ISSUE TITLE
[Bug]: Adding tag to post closes modal

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#540]
### Describe the bug

When adding a tag to an existing post the modal is closed. Our design shows the modal remains open, making it possible to add multiple tags without needing to click the post's tag button again. This was also the behaviour pre-nexus.

### Reproduce

1. Find a post in the feed to tag (or create one)
2. Click the tag button to display the Tag Post modal
3. Type a value for the post and click plus button to add
4. Observe the modal closes

### Web Browser

Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
Fixed, next release

**Comment by catch-21** [comment]
verified in a586206b8e222e73ff937a2f59960ab39abaede6
