### ISSUE TITLE
[Bug]: We are using Identicons wrong

### ISSUE THREAD

**Issue by Nuhvi** [pubky/pubky-beta#542]
### Describe the bug

Identicons are meant to be generated from Public keys, so storing it on Nexus is counter productive, but we also store just one identicon and use that as the fallback for absent avatars.

If we don't want to use identicons, find another placeholder.
If we want to use identicons, generate them from the Pubky so they look different even if not recognizable.

**Comment by flaviomoceri** [comment]
We probably don't even want to use Identicons, it was just a temporary image I used at first and it stayed 

Yes, please save a placeholder as a fallback, I don't know which one honestly

![image](https://github.com/user-attachments/assets/744f63be-b9cb-4574-80e7-63da8c5d414d)


If we want to use Identicons browser side I can only generate .svg, but I need .png, so "server" side if a user does not have the image it should automatically generate it for him and save it (but in my opinion it is a waste)

Browser: https://jdenticon.com/get-started/typescript.html
Server: https://jdenticon.com/get-started/node-js.html


maybe it is better to mention @aldertnl to create an appropriate placeholder user default image

**Comment by aldertnl** [comment]
I think using identicons is still useful, as it helps distinguish users that have not uploaded a profile pic yet. The problem is, a generic placeholder image will make all new users appear the same, visually.
