### ISSUE TITLE
[Bug]: Unable to bookmark a newly created post before refreshing page

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#545]
### Describe the bug

After creating a new post it is seen in the feed. At this point, attempting to bookmark it shows the success notification at the bottom and the button changes to indicate the post is bookmarked but a page refresh reveals the post was not actually bookmarked. Must refresh browser BEFORE bookmarking for it to succeed.

### Reproduce

1. Enter some text into quick post box and click 'Post'
2. Wait for post to appear in feed
3. Click on bookmark button for the newly created post
4. Observe the "Save as bookmark" notification at the bottom and the bookmark button highlights to indicate the post is now bookmarked
5. Navigate to own profile page
6. Observe the post is not included in the list of bookmarked posts.

### Web Browser

Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by MiguelMedeiros** [comment]
Fixed in the new flow.

**Comment by catch-21** [comment]
verified in current staging deployment
