### ISSUE TITLE
[Bug]: Unable to repost a newly create post before refreshing page

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#546]
### Describe the bug

After creating a new post it is seen in the feed. At this point, attempting to repost it shows the "Repost created" message the bottom of the screen but no new repost is seen in feed before or after page refresh. Must refresh browser BEFORE reposting for it to succeed.

### Reproduce

1. Enter some text into quick post box and click 'Post'
2. Wait for post to appear in feed
3. Click on repost button for the newly created post
4. Click repost button in the repost modal
5. Observe no new repost is seen in the feed, before or after a page refresh

### Web Browser

Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) (64-bit)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by MiguelMedeiros** [comment]
Fixed in the new flow.

**Comment by catch-21** [comment]
verified in current staging deployment
