### ISSUE TITLE
[Bug]: Reply ordering

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#560]
### Describe the bug

The current order of reply posts shows newer ones towards the top but our design (v6) shows the latest posts appearing below the others.

### Reproduce

1. View reply thread in the feed
2. and click on post to view reply thread in its own page
3. Observe the order of replies starts with the newest at the top

### Screenshots / Recording

| Design  | Actual |
| ------------- | ------------- |
| <img width="809" alt="Screenshot 2024-11-11 at 12 03 11" src="https://github.com/user-attachments/assets/a2f0589b-7254-409e-87c3-72a460a9b833"> | <img width="805" alt="Screenshot 2024-11-11 at 08 59 55" src="https://github.com/user-attachments/assets/f196b01b-d274-40b5-882e-9fb8182bbe0b"> |

### Web Browser

Version 130.0.6723.92 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
fixed, check next release

**Comment by catch-21** [comment]
Verified in 38a104b45aa86bd96f7466789077bf8c2933b16a
