### ISSUE TITLE
[Bug]: Post and Article max lengths do not match backed limits

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#564]
### Describe the bug

Nexus allows up to 1_000 chars for a post and 50_000 chars for long form but pubky-app is currently limiting to 300 and 1_000 chars respectively.
This is currently the case on `dev` and `article-2` branches.

### Reproduce

1. Click post button in bottom right corner
2. Observe the counter says `0 / 300`
3. Click the article button to show article creation view
4. Observe the counter says `0 / 1000`

### Web Browser

Version 130.0.6723.92 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
fixed, check next release

**Comment by catch-21** [comment]
Verified in current staging deployment
