### ISSUE TITLE
Add telegram link to Settings Help page

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#567]
### Describe the problem

The Help Settings page has a disabled button for Support.

### Describe the solution

This can be linked to the telegram group t.me/pubkychat.

### Additional context

<img width="667" alt="Screenshot 2024-11-11 at 20 06 29" src="https://github.com/user-attachments/assets/881621b3-3ac5-44aa-956d-b55be63e7ac6">

**Comment by flaviomoceri** [comment]
fixed, check next release

**Comment by flaviomoceri** [comment]
I checked in staging and it seems fixed, if I'm wrong please reopen the issue

**Comment by catch-21** [comment]
Yes thanks. I didn't close because I was checking if this is the best link to use. It is.
