### ISSUE TITLE
[Bug]: Sign in with seed phrase can force user to add new profile data without an option to exit

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#569]
### Describe the bug

At sign in, if a seed phrase is entered that doesn't have a profile then the user is taken to the registration page to add the profile info. The problem is, if you entered the seed phrase in error (e.g. typo, easily done) then you cannot now go back to try again; you are stuck at the register page due to redirects and forced to add a new user profile.

### Reproduce

1. Go to Sign In page
2. Enter any values for the 12 seed words (can be garbage, there are no rules)
3. Click 'Sign In' button
4. Because this seed doesn't have a profile, you are redirected to the registration page to enter new profile info
5. All attempts to leave force you back to registration page:
  - Navigate back in browser
  - Click on Pubky logo
  - Type other pubky url (e.g. /sign-in or /)

### Screenshots / Recording

https://github.com/user-attachments/assets/8c7d2d23-a501-432f-b565-708a81e1ed0b

### Web Browser

Version 130.0.6723.92 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by catch-21** [comment]
This also occurs when signing in with backup file that doesn't have profile associated with it (one created in a different environment or has been deleted)

**Comment by flaviomoceri** [comment]
fixed, try next release

**Comment by catch-21** [comment]
Verified in latest staging build. No longer possible to proceed with invalid seed, a seed that has no profile associated, or a file produced from a different environment.
