### ISSUE TITLE
[Bug]: Adding new profile name shorter than 3 chars can cause indefinite spinning of Finish button

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#570]
### Describe the bug

Signing in with a seed phrase that has no profile associated with it takes the user to the registration page. At this stage, if a profile name less than 3 chars in length is used then the Finish button gets stuck loading indefinitely and it is not possible to change the profile name to a suitable length.

### Reproduce

1. Go to Sign In page
2. Enter a seed phrase that hasn't been used before
3. After being navigated to the registration page, enter a profile name less than 3 chars long
4. Click 'Finish' button
5. Observe Finish button spins indefinitely and it is not possible to edit the profile name to try making it a correct length. Page refresh required.
6. Also observe the "minimum length" error overlaps the pubky value

### Screenshots / Recording

https://github.com/user-attachments/assets/7011950d-c1e5-4739-a6ed-18dfe749e0d4

### Web Browser

Version 130.0.6723.92 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
fixed, check next release

**Comment by catch-21** [comment]
Verified in latest staging deployment. It is possible to get to the registration page this way now.

**Comment by catch-21** [comment]
Using 342cb8fac3f51c92ea9375fabe45df5940b879a4
This has come back. Probably due to https://github.com/pubky/pubky-app/pull/619

**Comment by flaviomoceri** [comment]
@catch-21 please use just dev branch

**Comment by catch-21** [comment]
Verified in 6385ffbd02634751e6333ba28bffe85881ae0a2f
