### ISSUE TITLE
Feat: add `button medium`

### ISSUE THREAD

**Issue by flaviomoceri** [pubky/pubky-beta#58]
![Screenshot 2024-02-08 170646](https://github.com/synonymdev/social-ui-monorepo/assets/63161412/cb9a8f8e-a20f-45ca-9561-79c507367451)

**Comment by MiguelMedeiros** [comment]
Rename it to: Button/Medium
Lets follow the figma naming, bc this button could be used by other things than only tags.
![image](https://github.com/synonymdev/social-ui-monorepo/assets/5798170/706dd199-cffc-4e11-9c80-8902251f4e2b)
