### ISSUE TITLE
[Bug]: Post with image upload shows empty post in feed immediately after

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#610]
### Describe the bug

This appears to be due to pubky app requesting null image
https://nexus.staging.pubky.app/v0/files/file/null

A manual page refresh displays the uploaded image correctly

### Reproduce

1. Attach image in quick post and click Post button
2. Observe new empty post at top of feed

### Screenshots / Recording

![Screenshot_20241115_161226](https://github.com/user-attachments/assets/3a85a2b5-7fb3-4d72-bbd4-4bf98ea91b28)

### Web Browser

Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)

### Pubky App Version

a586206b8e222e73ff937a2f59960ab39abaede6

**Comment by MiguelMedeiros** [comment]
Fixed in the new flow.

**Comment by catch-21** [comment]
Verified in current staging deployment
