### ISSUE TITLE
[Bug]: Unable to run `nx serve intro`

### ISSUE THREAD

**Issue by flaviomoceri** [pubky/pubky-beta#611]
### Describe the bug

If I try to run nx serve intro, it shows an error:

![Screenshot from 2024-11-15 12-37-40](https://github.com/user-attachments/assets/9a8b3cdd-daf2-416b-b042-47df881d4f0b)

**Comment by MiguelMedeiros** [comment]
We will not use the intro website anymore, so I will close this issue for now.
