### ISSUE TITLE
[Feature]: Display whole links on profile page, no truncation

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#708]
### Describe the problem

Even links with a normal length are not displayed entirely in the profile page.

e.g. https://bsky.app/profile/pubky.app
![Screenshot_20241202_111501](https://github.com/user-attachments/assets/da0a20fb-ae5b-481f-a06c-b004edbf1567)

### Describe the solution

There is enough space so we should display the whole link unless it is very long.

**Comment by flaviomoceri** [comment]
Seems already fixed in dev branch @catch-21

**Comment by catch-21** [comment]
What I see on dev eaa4a5e3666e9502e06aa1e0557174fb0549f29f is still truncated. Most of what is seen is the less-useful part of the url that excludes the personal bit.
![Screenshot_20241203_160729](https://github.com/user-attachments/assets/be52ad17-e0b0-4d03-9f02-d91e9de9e4f5)

**Comment by catch-21** [comment]
verified in d6bc94ef626a48765203ce8d151ff995752ab361
![image](https://github.com/user-attachments/assets/6d0b6bb9-0c34-454d-bd7a-493135b963e3)
Not sure how I feel about this wrapping but its an improvement on the truncation so lets leave it be for now.
