### ISSUE TITLE
[Bug]: No UI error when httprelay used by pubky-ring is erroring

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#735]
### Describe the bug

The demo.httprelay.io that we use for pubky-ring sign up and sign in is currently responding 503 due so some issue on their end. This has caused the QR sign up and sign in to stop working. There is no indication in the UI, it simply does nothing when QR is scanned and authorised in the pubky-ring app.

We should show a UI error with a useful suggestion when this service is either errorring or is unreachable.

### Reproduce

1. Go to sign in page
2. Attempt to sign in with pubky-ring app by scanning the QR
3. Pubky-app does not proceed to sign in
4. Network debug shows http relay returned 503 error

### Web Browser

Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)

### Pubky App Version

355da2010b3fba9d88426402d888d12abd7f1ee2

**Comment by flaviomoceri** [comment]
Currently I receive an error because the relay is down, so I do not show the qrCode, but in the future from the promise I should receive an error message if the auth via pubky ring does not go well

**Comment by weedcoder** [comment]
i put this issue in my kanban.
i'll update the status when i found where and how to run httprelay in internally.

**Comment by weedcoder** [comment]
it will take me half a day to put it in staging env. will do it tomorrow 2024-12-11

**Comment by weedcoder** [comment]
httprelay is installed on staging environment on the reverse proxy.

https://httprelay.staging.pubky.app/health

**Comment by weedcoder** [comment]
i added
```NEXT_PUBLIC_DEFAULT_HTTP_RELAY=https://httprelay.staging.pubky.app/link```
to the pubky-app env file on staging.

**Comment by weedcoder** [comment]
can we close ?

**Comment by catch-21** [comment]
Error is now shown when request times out
