### ISSUE TITLE
[Feature]: Grok link preview in post

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#743]
### Describe the problem

Links to Grok are not previewed

![Screenshot_20241216_111324](https://github.com/user-attachments/assets/c27555d7-c9bf-45d0-8818-def3e6cbdeb7)

### Describe the solution

We should provide some preview, or at least include some description of the link such as what is done (perhaps by chance) with ChatGPT.

### Additional context

![Screenshot_20241216_111311](https://github.com/user-attachments/assets/1406c419-a93e-4594-b42f-d200a999e094)

**Comment by flaviomoceri** [comment]
It does not depend on us, it depends on the SEO of that page, we try to display title, description and image

if they are available we display them, I tried to console.log to see the data we have and I do not have any particular element to create a custom preview like the one I used for Github for example and there is no external library that easily generates a preview for grok yet, at least for now

**Comment by catch-21** [comment]
Ok, not in our control. Closing.
