### ISSUE TITLE
[Bug]: Wrong notification text when tagging a post

### ISSUE THREAD

**Issue by SeverinAlexB** [pubky/pubky-beta#752]
### Describe the bug

I tagged [Ars post](https://staging.pubky.app/post/pxnu33x7jtpx9ar1ytsi4yxbp6a5o36gwhffs8zoxmbuptici1jy/0032JWQNGNHD0). When Ar [reposted his own post](https://staging.pubky.app/post/pxnu33x7jtpx9ar1ytsi4yxbp6a5o36gwhffs8zoxmbuptici1jy/0032JWRMQGFVG) (and he edited it too perhaps? @Nuhvi), I received a notification that "[Nuh 🔻](https://staging.pubky.app/profile/pxnu33x7jtpx9ar1ytsi4yxbp6a5o36gwhffs8zoxmbuptici1jy) edited a post you reposted". I never reposted his post though.

### Reproduce

Not sure because it involved two people. I guess:
1. User A posts a post.
2. User B tags the post.
3. User A repost the post.
4. User A edits the repost.
5. User B should receive this weird notification.

Maybe?

### Screenshots / Recording

![CleanShot 2024-12-17 at 09 44 02@2x](https://github.com/user-attachments/assets/0ee9eb5e-6569-461c-b378-4433f782dd8a)
![CleanShot 2024-12-17 at 09 44 21@2x](https://github.com/user-attachments/assets/efc1c4e6-0f42-45f3-95a1-e529646bf3b8)

### Web Browser

Brave Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (arm64)

### Pubky App Version

Current Staging

**Comment by Nuhvi** [comment]
I did edit it.
