### ISSUE TITLE
[Bug]: White border on profile photo

### ISSUE THREAD

**Issue by JeanlChristophe** [pubky/pubky-beta#756]
### Describe the bug

![Screenshot 2024-12-17 at 12 36 01](https://github.com/user-attachments/assets/66b7ebda-fc64-46b0-819e-793e3ca00e72)
![Screenshot 2024-12-17 at 12 36 43](https://github.com/user-attachments/assets/36317a41-f03c-4adf-909c-2ad5645a9a41)

**Comment by flaviomoceri** [comment]
I checked figma and everything seems ok, that white border is intentional

I'm closing the bug, if I'm wrong please reopen it and provide more details
